### ISSUE TITLE
How did you get reviews from zomato

### ISSUE THREAD

**Issue by chinesh** [anirudhagar13/Zomato-Food-Review#14]
please help me at 
Email: chinesh4@gmail.com

**Comment by rohangarwal** [comment]
We used the zomato api. However they do not provide access to all the reviews of the restaurant via the API.

**Comment by anirudhagar13** [comment]
The Zomato API provides limited reviews while we needed a substantial number. Thus, we ended up scraping data from Zomato site, for all the restaurants that we subsumed in our project.
